FROM python:3.10-slim AS compile-image

RUN apt-get update \
 && apt-get install --no-install-recommends build-essential gcc -y

WORKDIR /usr/src/app

COPY requirements.txt setup.py README.rst ./
COPY myapp/ ./myapp/

RUN python -m pip install --upgrade pip \
 && python -m pip install --user -r requirements.txt \
 && python -m pip install --user .

ENV PATH="/root/.local/bin:$PATH"

CMD python -m myapp